name: School CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Build and Test
        run: |
          xcodebuild clean test \
            -project SchoolDemoCICD.xcodeproj \
            -scheme SchoolDemoCICD \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15'
